language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit -c tests/build.xml

notifications:
    on_success: never
    on_failure: always